services:
  backend:
    build: backend

  frontend:
    build: frontend
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: [ "start-dev" ]
    depends_on:
        - db

  db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-scripts:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80" # Mappt den Port 80 des Hosts auf den Port 80 des Containers
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mountet die Konfigurationsdatei ins NGINX-Verzeichnis
    restart: always

volumes:
  db_data:
